using Homon.Domain.Monitoring;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Homon.Infrastructure.Persistence.Configurations;

internal sealed class ProbeObservationConfiguration : IEntityTypeConfiguration<ProbeObservation>
{
    public void Configure(EntityTypeBuilder<ProbeObservation> builder)
    {
        builder.ToTable("ProbeObservations");

        builder.HasKey(o => o.Id);

        // Npgsql's default GENERATED BY DEFAULT AS IDENTITY for a long key with
        // ValueGeneratedOnAdd — an append-only, time-ordered, high-volume table is the one
        // place a random-order Guid key would actively hurt (index bloat, no clustering
        // benefit); see plan 002's "Defaults taken".
        builder.Property(o => o.Id)
            .ValueGeneratedOnAdd();

        builder.Property(o => o.ObservedAt)
            .IsRequired();

        builder.Property(o => o.Succeeded)
            .IsRequired();

        // Composite index on (ProbeId, ObservedAt): the same index the uptime and sparkline
        // queries need (both filter by ProbeId and a date range) and the one the retention
        // sweep's WHERE clause scans. One index serves all three — see Decision 6. Postgres
        // does not index a foreign key on its own, so this also covers the FK itself.
        builder.HasIndex(o => new { o.ProbeId, o.ObservedAt });

        builder.HasOne<Probe>()
            .WithMany()
            .HasForeignKey(o => o.ProbeId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
